Fix precedence problem by replacing or with ||
Ensembl/zircon pull request #1
Opened 2019-02-06 12:48 UTC by thibauthourlier

Since Perl 5.22, it warns of possible precedence problem it cases
like : return $value or die('Sad');
return $value is tested, not $value. It can be fixed by either using
|| or by using () around the test.
The problem was already there in earlier versions of Perl but no
waring was issued.

2019-03-20 10:55 UTC, tgrego reviewed
In my opining the proper fix would be to stop using or/|| altogether...
``` perl
if (!$self->{zconn}) {
  die "Need zconn set now";
}
return $self->{zconn};
```

and since we're at it using confess instead of die could be helpful.

2019-04-02 16:19 UTC, mira13 approved these changes

2019-04-05 12:42 UTC, mkszuba requested changes
I am with Tiago on this one, as it is the fix might actually make the code work correctly but it won't make it any easier to read.

2019-04-15 08:44 UTC, thibauthourlier commented
I've made the changes requested, by adding an if statement and using confess instead of die

2019-04-23 08:54 UTC, tgrego approved these changes

2019-04-23 09:54 UTC, mkszuba approved these changes
I've just realised the actual assignment of _$self->{zconn}_ looks pretty awkward too - but that's beyond the scope of this PR. Approved.

2019-04-23 09:54 UTC, merged